name: assistant
instructions: You are a helpful assistant.
example_conversations:
  - messages:
    - user: user
      text: Who won the world series in 2020?
    - user: assistant
      text: The Los Angeles Dodgers won the World Series in 2020.
    - user: user
      text: Where was it played?
    - user: assistant
      text: The 2020 World Series was played entirely at Globe Life Field in Arlington, Texas due to the COVID-19 pandemic.